modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "highspeed"
version = "${version}"
displayName = "Create: Highspeed"
authors = "OneLink, BlahajtheShark14"
description = '''
Create: Highspeed is an addon for create that adds many high-speed rail features, including a new type of rail, maglev, which allows for higher speeds than normal tracks.
'''
logoFile = "highspeedlogo.png"

[[dependencies.highspeed]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.highspeed]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.highspeed]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"