modLoader = "javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "https://github.com/OneLinkPog/accelerate/issues"
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "accelerate"
version = "${version}"
displayName = "Create: Accelerate"
displayURL = "https://modrinth.com/project/create-accelerate"
authors = "OneLink, BlahajTheShark14"
description = '''
Create: Accelerate is an addon for create that adds many high-speed rail features, including a new type of rail, maglev, which allows for higher speeds than normal tracks.
'''
logoFile = "./acceleratelogo.png"

[[dependencies.accelerate]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerate]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerate]]
modId="create"
mandatory=true
versionRange="[6.0.8,6.1.0)"
ordering="NONE"
side="BOTH"
