modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "CC BY-NC-SA 4.0"

[[mods]]
modId = "createmaglev"
version = "${version}"
displayName = "Create: Maglev"
authors = "OneLink"
description = '''
Create: Maglev is an addon for create that adds a new type of rail, maglev, which allows for higher speeds than normal tracks.
'''
logoFile = "icon.png"

[[dependencies.createmaglev]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createmaglev]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createmaglev]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"